package com.example.etl_app.models

enum class ProductCategory{
    GROCERY,GENERAL_ITEMS,CLOTHING,FOOD,ELECTRONICS,STATIONARY,BAKERY,MEDICAL_ITEMS,FARMING_ESSENTIALS,GIFT_ITEMS,APPAREL
}

enum class PaymentMode{
    COD,UPI,DEBIT_CARD,CREDIT_CARD,NET_BANKING
}

enum class OrderStatus{
    ORDERED,APPROVED,REJECTED,PROCESSING,OUT_FOR_DELIVERY,DELIVERED,CANCEL_REQUESTED,CANCEL_APPROVED,CANCEL_REJECTED,CANCELLED,RETURN_REQUESTED,RETURN_APPROVED,RETURN_REJECTED,RETURN_OUR_FOR_DELIVERY,RETURNED
}